version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: armatuxpc-postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - armatuxpc-net
    # ‚ùå NO exponemos el puerto

  backend:
    build:
      context: ./backend/ArmatuXPC.Backend
      dockerfile: Dockerfile
    container_name: armatuxpc-backend
    restart: always
    depends_on:
      - postgres
    environment:
      - ConnectionStrings__DefaultConnection=${ConnectionStrings__DefaultConnection}
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5000:8080"
    networks:
      - armatuxpc-net

volumes:
  postgres_data:

networks:
  armatuxpc-net:
    driver: bridge
